### ISSUE TITLE
parallel composition  to keen to end

### ISSUE THREAD

**Issue by davidstreader** [davidstreader/Model-Checker#6]
Two parallel processes only terminate successfully if both terminate successfully.  See
processes {
A = (a->x->b->STOP).
X = c->x->d->X.
 C = A||X.
}
automata A,X,C.

![image](https://user-images.githubusercontent.com/2947174/36232750-dc175fa0-1247-11e8-869d-dd185f4fdb01.png)

Note process X never terminates so nor should process C.  
This causes problems with  
C=>(z->STOP).

**Comment by NHAS** [comment]
Its being marked STOP on line 71 in AutomataReachability.java

" automaton.getNodes().stream()
        .filter(node -> node.getOutgoingEdges().size() == 0 && !node.isTerminal())
        .forEach(node -> node.setTerminal("STOP"));"

However this indicates that its not being set as a terminal ERROR state anyway, as "!node.isTerminal()" would prevent it from resetting an already set state.
